### ISSUE TITLE
Get bvec/bavl files for diffusion when using BIDS

### ISSUE THREAD

**Issue by manuegrx** [populse/mri_conv#13]
In a BIDS folder, for diffusion data, ".bvec" and ".bval" files are already created (with the same name as the NIfTI file except for the extension) 
As discussed together, it would be useful to keep those files and to be able to export them in the same folder as the NIfTI/json pair in order to sued them in MIA for example.

**Comment by montigno** [comment]
Hi,

A new version of mri_conv is available (23.4.0a). 

Please keep me informed.

Olivier

**Comment by manuegrx** [comment]
Hi, 

It works, thank you ! 
Bvec and bval are correctly import into the mia raw_data folder. For now, they are not in the database, if needed I will check how to add them. 

Emmanuelle

**Comment by servoz** [comment]
Shouldn't bval and bvec be indexed directly in the database, like other data, when they are imported into Mia (more specifically in the folder known by Mia as raw_data)?

Would it be sufficient for them to be present in the json used for indexing at the time of import into Mia (like all other imported and indexed data)? Or is there some other constraint/reason I'm missing?

I think the current paradigm should be that data imported (or known/created as a result of a calculation) into Mia is indexed, as far as possible, in the database.

**Comment by manuegrx** [comment]
You right, I think It will better to have the bvec/bval indexed in the database (It will be helpfull for some mrtrix bricks for example)

Should change in mri_conv or in Mia ?

**Comment by servoz** [comment]
It's been a while since I've worked on this part of the code, but I think we can [find it here](https://github.com/populse/populse_mia/blob/211ef63fbad10664ef987d22c67cecd54f84d697/populse_mia/data_manager/data_loader.py#L137).

Things are collected by Mia in the logExport*.json file which, unless I'm mistaken, is sent by mri_conv ... to be checked ...

**Comment by montigno** [comment]
Yes, we could add this kind of information in the logExport. 

See me to discuss it better. 


De: "Eric Condamine" ***@***.***> 
À: "populse/mri_conv" ***@***.***> 
Cc: "OLIVIER MONTIGON" ***@***.***>, "Comment" ***@***.***> 
Envoyé: Vendredi 25 Août 2023 12:33:08 
Objet: Re: [populse/mri_conv] Get bvec/bavl files for diffusion when using BIDS (Issue #13) 





It's been a while since I've worked on this part of the code, but I think we can [ https://github.com/populse/populse_mia/blob/211ef63fbad10664ef987d22c67cecd54f84d697/populse_mia/data_manager/data_loader.py#L137 | find it here ] . 

Things are collected by Mia in the logExport*.json file which, unless I'm mistaken, is sent by mri_conv ... to be checked ...

**Comment by servoz** [comment]
If the bval and bvec files are in the json sent by mri_conv, this means that the [run() method needs to be modified](https://github.com/populse/populse_mia/blob/211ef63fbad10664ef987d22c67cecd54f84d697/populse_mia/data_manager/data_loader.py#L137). ...

 It may be that this method only retrieves .nii files, or that there is some other limitation (I haven't reread the method!).

To be checked ...

**Comment by manuegrx** [comment]
The bval and bvec files are in separate file (.bvec and .bval) in the raw_data folder. 

I will check this method to understand why they are not automatically indexed

**Comment by manuegrx** [comment]
For now,  .bvec and .bval files are not in the json sent by mri_conv. 
@montigno I will come to see you to discuss about this next week 

It will be also necessary to add .bval and .bvec in the popusle_mia method (as you thought @servoz only .nii are managed for now)

**Comment by servoz** [comment]
>>> The bval and bvec files are in separate file (.bvec and .bval) in the raw_data folder.

Yes, but if I remember correctly these are txt files, and I suspect that the run() method is actually only designed for nii files ...
And then there are the tags ... If I still remember correctly they are retrieved from the json file associated with the nii file (which is why I think run() was originally written for nii/json files).

If there is no json associated with the files for bval and bvec I don't think it will work ...

As always, a small problem, long time to fix ...

In any case, if we had only written this part for nii/json at the start, I think it would be interesting to be able to import other types of files. Here, bval and bvec are an good example!

@manuegrx take heart, the summit is not far away !!!! but it hides the next :-)))))))

**Comment by montigno** [comment]
A new version of mri_conv is available (23.4.1a). 




A 'bvec_bval' tag has been added in the LogExport (= 'yes' if bvec and bval files have been created or copied).

**Comment by manuegrx** [comment]
Thank you @montigno

**Comment by montigno** [comment]
A new version of mri_conv is available (23.4.2a). 

bvec and bval files have now .bvec and .bvac extensions (FSL format). 

The MRtrix format stay as before (.txt)

**Comment by manuegrx** [comment]
Thank you @montigno  ! 

However, if we want the "real" FSL format we should also change the way the bvec / bval are reported in the files (sorry I missed this part during our chat yesterday) , I open an other issue to explain more in details https://github.com/populse/mri_conv/issues/14
